# This script depends on two environment variables to be set in Bitbucket Pipelines

image: node:10.15.3

# Doing a full clone to be able to push back to Heroku.
clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - yarn install
          - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
